### ISSUE TITLE
Peer disconnects after 20 minutes

### ISSUE THREAD

**Issue by deweller** [Bit-Wasp/bitcoin-p2p-php#34]
After 20 minutes, the connection to the bitcoin node drops.  This behavior is happens consistently.

I tried sending a ping periodically, but that made no difference.

Do you have any idea what might cause this?  Is a socket connection timing out?  Is there a config setting on the bitcoind side that controls this?

Thanks.

**Comment by afk11** [comment]
I'll look into this, seems strange. I've left two peers pinging eachother, we'll see if they last the night! 

As for if it's bitcoind,

**Comment by deweller** [comment]
I logged a `debug_backtrace` from the close listener and this does appear to be coming from the other side (bitcoind).

```
Peer.php, 251: close
[unknown file], [unknown line]: BitWasp\Bitcoin\Networking\Peer\{closure}
EventEmitterTrait.php, 64: call_user_func_array
Stream.php, 98: emit
[unknown file], [unknown line]: close
EventEmitterTrait.php, 64: call_user_func_array
Buffer.php, 75: emit
Buffer.php, 65: close
Stream.php, 119: end
Stream.php, 136: end
[unknown file], [unknown line]: handleData
StreamSelectLoop.php, 227: call_user_func
StreamSelectLoop.php, 201: waitForStreamActivity
Listener.php, 63: run
run.php, 25: run
```

My script listens to `inv` events and requests transaction data whenever it receives a new transaction notification.

It receives a close event consistently every 20 minutes.

**Comment by afk11** [comment]
I tested two peers and they remained stable for an hour, so it does look like bitcoind. There is code in Core that disconnects based on certain factors, but I can't be sure if it's due to this. I did get the impression any whitelisted peers would not be disconnected, so adding it to bitcoinds conf might help as a temporary measure. 

Ideally, we would force bitcoind to keep the connection open, but we'd have to behave like a normal peer. Maybe syncing new headers as they're published?

**Comment by deweller** [comment]
Whitelisting my PHP node didn't help.

I turned `net` level debugging on in my bitcoin.conf settings, and I found following debug log entry:

```
2015-12-14 13:58:24 ping timeout: 1200.033522s
2015-12-14 13:58:24 disconnecting peer=12
```

So it looks like bitcoind is trying to ping my php node and is not getting a response.  So, I'm guessing I need to write some code to let my node respond to pings.

**Comment by deweller** [comment]
And, sure enough, after implementing a method to receive ping messages and respond with a pong, bitcoind no longer drops the connection after 20 minutes.

It seems so obvious now.  ;)

Thanks for your help on this.
