### ISSUE TITLE
Using Other Networks than Bitcoin

### ISSUE THREAD

**Issue by stefanhuber** [Bit-Wasp/bitcoin-p2p-php#72]
Currently the `Peer->send()` only serializes for the Bitcoin network, as no `NetworkInferface` parameter is provided.
https://github.com/Bit-Wasp/bitcoin-p2p-php/blob/master/src/Peer/Peer.php#L127

The easiest approach IMHO would be to add a `getNetwork()` method in the Message Factory and call this inside the `Peer`. I will create a pull request...

Maybe not the most beautiful solution though...

**Comment by afk11** [comment]
Closing this issue, as the connected PR has been merged! Thanks again :)
